COLUMNS:
  RowNumber: int64
  CustomerId: int64
  Surname: str
  CreditScore: int64
  Geography: str
  Gender: str
  Age: float64
  Tenure: int64
  Balance: float64
  NumOfProducts: int64
  HasCrCardl: float64
  IsActiveMember: float64
  EstimatedSalary: float64
  Exited: int64


TARGET_COLUMN:
  name: Exited